name: CI

on:
  push:
    branches:
    - master
    - release/*
    - develop
    - features
  pull_request:
    branches:
    - master
    - release/*
    - develop
    - features

jobs:
  run:    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.1', '7.2', '7.3']
    name: PHP ${{ matrix.php-versions }}
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-versions }}
        extension-csv: mbstring, curl, ctype, gdlib, xdebug, apcu
    - name: Check PHP Version
      run: php -v
    - name: Check Composer Version
      run: composer -V
    - name: Install composer
      run: composer install --ignore-platform-reqs
    - name: Check PHP Extensions
      run: php -m  
    - name: Run PHPUnit
      run: phpunit
